apiVersion: v1
kind: ConfigMap
metadata:
  name: qbittorrent-config
data:
  qBittorrent.conf: |
    [Preferences]
    # This sets the password to "changeme" - you should change this!
    WebUI\Password_PBKDF2="@ByteArray(ARQ77eY1NUZaQsuDHbIMCA==:0WMRkYTUWVT9wVvdDtHAjU9b3b7uB8NR1Gur2hmQCvCDpm39Q+PsJRJPaCU51dEiz+dTzh8qbPsL8WkFljQYFQ==)"
    WebUI\Username=admin
    WebUI\Port=80