---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prowlarr
  namespace: default
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 2Gi
  storageClassName: longhorn
  volumeName: prowlarr-restored-pv 