apiVersion: v1
kind: Secret
metadata:
  name: alertmanager-secret
  namespace: observability
type: Opaque
stringData:
  ALERTMANAGER_HEARTBEAT_URL: ENC[AES256_GCM,data:TyIYPpA50jkf/OH2QT03jKJYgtW9faxeKr8njMoAhYN8ykAqqnw7wF9AkgmzVGaTOOHmmsHOuTM=,iv:GSGrjNHYYJprBhmenpXsrFS4R2Ugn3rEaR+f57/Nebw=,tag:0IMIaTeqh71L/dAL/14lFA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNeG1WM3o5Uk5oNXhYc3gv
        bmFKRG9wSWw5VnhBTGdCZ1RwWDdYNlNSazNvCmdNYnlQeWhrc0NsQ3c5Vkx4S284
        Z01XVnlTc1NMZU13RWxibFlDd1hwOEkKLS0tIEN0YmZPKzlYK0NoQldnVnJ5OEpI
        c1lObnpSQWp3NW42Y0poZXNBdlJ4dGcKMoaGIF1/m0d4qQnA5jQhA44MA+G5Izkv
        DDFjsxuZHI3TIWhstNZGYJ5mRq9r/OfOK37iFeBu/EI5O46yJDX8Og==
        -----END AGE ENCRYPTED FILE-----
      recipient: age169tkyzjgmevv6qsm63yvmw5esv3d0mgpl85phljxw7ku235904pqg8qg3l
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-30T08:14:44Z"
  mac: ENC[AES256_GCM,data:+IZaclm6ssqImeIv2J1c1+OV15ZWhc/KXokpABT884bF0KYXinoD25e77uLKoT5rwoetKK2+abHMN6UOgaA9lQlLp9j5FzJneQuct/6OCaw+D9u9yZZJ/kYA51nOGNgS2pB0gyrpE2GWhRtiPB3Hjp7140Ag5MxHMIL30HXNi0c=,iv:yYCSOpWusNCUI6Uxe+wfKEtqdXNhaPCJqjKuSkbhp8c=,tag:e/S04XNrjj4JCDzX59FL0A==,type:str]
  mac_only_encrypted: true
  version: 3.13.1
