apiVersion: v1
kind: Secret
metadata:
  name: alertmanager-secret
  namespace: observability
type: Opaque
stringData:
  ALERTMANAGER_HEARTBEAT_URL: ENC[AES256_GCM,data:TyIYPpA50jkf/OH2QT03jKJYgtW9faxeKr8njMoAhYN8ykAqqnw7wF9AkgmzVGaTOOHmmsHOuTM=,iv:GSGrjNHYYJprBhmenpXsrFS4R2Ugn3rEaR+f57/Nebw=,tag:0IMIaTeqh71L/dAL/14lFA==,type:str]
  DISCORD_WEBHOOK_URL: ENC[AES256_GCM,data:Msbu3bSNFXbu+536Zu3kIZCVE3VgyINm3ct1D6JJgcnh5ZEowirF7vCH4+kROE71Za0N1kpxW08Bm8Jf3K/08ucQNaS9xXXbtx8H4+XZigSaTHBpRmtuDB5B1uRhWx34k/T9s6MfP4wcUPXfnPOJrgWYwene83PrzQ==,iv:dLsi7nc9iojHTbBI9Tr/+ET1d7EQ3oFX9UfuULNfu1Y=,tag:QdoMgnENqbh98RdI6M8KQA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNeG1WM3o5Uk5oNXhYc3gv
        bmFKRG9wSWw5VnhBTGdCZ1RwWDdYNlNSazNvCmdNYnlQeWhrc0NsQ3c5Vkx4S284
        Z01XVnlTc1NMZU13RWxibFlDd1hwOEkKLS0tIEN0YmZPKzlYK0NoQldnVnJ5OEpI
        c1lObnpSQWp3NW42Y0poZXNBdlJ4dGcKMoaGIF1/m0d4qQnA5jQhA44MA+G5Izkv
        DDFjsxuZHI3TIWhstNZGYJ5mRq9r/OfOK37iFeBu/EI5O46yJDX8Og==
        -----END AGE ENCRYPTED FILE-----
      recipient: age169tkyzjgmevv6qsm63yvmw5esv3d0mgpl85phljxw7ku235904pqg8qg3l
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-25T19:02:25Z"
  mac: ENC[AES256_GCM,data:5ZIFjRU18I5mvVC3OuWTLYNCxtp3p3W9K7qRHZFodHtLtuZqxL5ycRySVxR5LZPX7D9dh2pe3NobxSP6kWo1F7YXg3jwV7cFl/Q476oQxBlrMFIglw2SJ/Mu8dsmb7nYGm8lcqDReCcUP44IQ2YYQlRYLzUgcrPp4AropD4ZIHY=,iv:sGPId+FU9aezPSnKR7OsncEnxAXlDH6Zhnb4uZnBDuo=,tag:uif+v9f/Wd4sMTmt8cEYew==,type:str]
  mac_only_encrypted: true
  version: 3.13.2
