services:
  - Infrastructure:
      - Traefik:
          icon: https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons@master/svg/traefik.svg
          href: https://traefik-cloud.${SECRET_DOMAIN}
          description: Ingress Controller/RP Cloud
          widget:
            type: traefik
            url: https://traefik-cloud.${SECRET_DOMAIN}
            username: ${HOMEPAGE_VAR_TRAEFIK_CLOUD_USERNAME}
            password: ${HOMEPAGE_VAR_TRAEFIK_CLOUD_PASSWORD}
      - Proxmox:
          icon: https://raw.githubusercontent.com/walkxcode/dashboard-icons/0eaf38572d4b8a2485228eb5da98d356ca47f653/svg/proxmox.svg
          href: https://proxmox.${SECRET_DOMAIN}
          description: PX-Cluster
          ping: 10.57.57.254
          widget:
            type: proxmox
            url: https://10.57.57.254:8006
            username: ${HOMEPAGE_VAR_PROXMOX_USERNAME}
            password: ${HOMEPAGE_VAR_PROXMOX_PASSWORD}
      - PBS:
          icon: https://raw.githubusercontent.com/walkxcode/dashboard-icons/0eaf38572d4b8a2485228eb5da98d356ca47f653/svg/proxmox.svg
          href: https://backup.${SECRET_DOMAIN}
          description: Backup Central
          ping: 10.57.57.253
          widget:
            type: proxmoxbackupserver
            url: https://10.57.57.253:8007
            username: ${HOMEPAGE_VAR_PBS_USERNAME}
            password: ${HOMEPAGE_VAR_PBS_PASSWORD}
            fields: ["datastore_usage", "failed_tasks_24h", "cpu_usage", "memory_usage"]
      - Synology:
          icon: https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons@master/svg/synology.svg
          href: https://storage.${SECRET_DOMAIN}
          description: NFS/SMB/Backup
          ping: 10.57.57.201
          widget:
            type: diskstation
            url: https://10.57.57.201:5001
            username: ${HOMEPAGE_VAR_SYNOLOGY_USERNAME}
            password: ${HOMEPAGE_VAR_SYNOLOGY_PASSWORD}
            volume: volume_1
      - Grafana:
          icon: https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons@master/svg/grafana.svg
          href: http://192.168.57.2:3000
          description: Monitoring Cloud + OnPrem
          ping: 192.168.57.2
          widget:
            type: grafana
            url: http://192.168.57.2:3000
            username: admin
            password: ${HOMEPAGE_VAR_GRAFANA_PASSWORD}
  - Media:
      - Jellyfin:
          icon: https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons@master/svg/jellyfin.svg
          href: https://jellyfin.k8s.${SECRET_DOMAIN}
          description: Media Streaming
          widget:
            type: jellyfin
            url: https://jellyfin.k8s.${SECRET_DOMAIN}
            key: ${HOMEPAGE_VAR_JELLYFIN_KEY}
      - Jellyseerr:
          icon: https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons@master/svg/jellyseerr.svg
          href: https://requests.k8s.${SECRET_DOMAIN}
          description: Media Requests
          widget:
            type: jellyseerr
            url: https://requests.k8s.${SECRET_DOMAIN}
            key: ${HOMEPAGE_VAR_JELLYSEERR_KEY}
      - Sonarr:
          icon: https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons@master/svg/sonarr.svg
          href: https://sonarr.k8s.${SECRET_DOMAIN}
          description: TV Shows Downloader
          widget:
            type: sonarr
            url: https://sonarr.k8s.${SECRET_DOMAIN}
            key: ${HOMEPAGE_VAR_SONARR_KEY}
      - Radarr:
          icon: https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons@master/svg/radarr.svg
          href: https://radarr.k8s.${SECRET_DOMAIN}
          description: Movies Downloader
          widget:
            type: radarr
            url: https://radarr.k8s.${SECRET_DOMAIN}
            key: ${HOMEPAGE_VAR_RADARR_KEY}
      - Prowlarr:
          icon: https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons@master/svg/prowlarr.svg
          href: https://prowlarr.k8s.${SECRET_DOMAIN}
          description: Media Indexer
      - qBittorrent:
          icon: https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons@master/svg/qbittorrent.svg
          href: https://qbittorrent.k8s.${SECRET_DOMAIN}
          description: Torrent Client
          widget:
            type: qbittorrent
            url: https://qbittorrent.k8s.${SECRET_DOMAIN}
            username: ${HOMEPAGE_VAR_QBITTORRENT_USERNAME}
            password: ${HOMEPAGE_VAR_QBITTORRENT_PASSWORD}
  - Network:
      - pFsense:
          icon: https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons@master/svg/pfsense.svg
          href: https://fw.${SECRET_DOMAIN}
          description: Firewall
          ping: 10.57.57.1
      - TP-Link:
          icon: https://www.svgrepo.com/show/102795/wifi.svg
          href: https://wifi.${SECRET_DOMAIN}
          description: WiFi Management
          ping: 10.57.97.143
      - MySpeed:
          icon: https://camo.githubusercontent.com/4ccc83cf6b1f06e999c378bda264433ec83994031c156a5c88876b53eb57b201/68747470733a2f2f692e696d6775722e636f6d2f61436d413672482e706e67
          href: https://speed.${SECRET_DOMAIN}
          description: Network Speed Test
          ping: 10.57.57.62
          widget:
            type: myspeed
            url: http://10.57.57.62:5216
      - Prometheus:
          icon: https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons@master/svg/prometheus.svg
          href: https://prometheus.k8s.${SECRET_DOMAIN}
          description: Metrics Monitoring
      - Alertmanager:
          icon: https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons@master/svg/alertmanager.svg
          href: https://alertmanager.k8s.${SECRET_DOMAIN}
          description: Alerting System
  - Development:
      - vsCode:
          icon: https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons@master/svg/vscode.svg
          href: https://vscode.${SECRET_DOMAIN}
          description: Visual Studio Code
          ping: 10.57.57.60
      - Portainer:
          icon: https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons@master/svg/portainer.svg
          href: https://cloud.${SECRET_DOMAIN}
          description: Docker Management
          ping: 192.168.57.2
      - Longhorn:
          icon: https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons@master/svg/longhorn.svg
          href: https://longhorn.k8s.${SECRET_DOMAIN}
          description: Persistent Storage
      - iDrac:
          icon: https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons@master/svg/idrac.svg
          href: https://idrac.${SECRET_DOMAIN}
          description: DELL R720 iDrac