- Infrastructure:
    - Proxmox Cluster:
        icon: https://raw.githubusercontent.com/walkxcode/dashboard-icons/main/svg/proxmox.svg
        href: https://proxmox.${SECRET_DOMAIN}
        description: Virtualization Platform
        ping: 10.57.57.254
        widget:
          type: proxmox
          url: https://10.57.57.254:8006
          username: "{{HOMEPAGE_VAR_PROXMOX_USERNAME}}"
          password: "{{HOMEPAGE_VAR_PROXMOX_PASSWORD}}"

    - Kubernetes Dashboard:
        icon: https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons@master/svg/kubernetes.svg
        href: https://kubernetes.${SECRET_DOMAIN}
        description: Kubernetes Dashboard

    # - Backup Server:
    #     icon: https://raw.githubusercontent.com/walkxcode/dashboard-icons/main/svg/proxmox.svg
    #     href: https://backup.${SECRET_DOMAIN}
    #     description: Proxmox Backup Server
    #     ping: 10.57.57.253

    - Synology NAS:
        icon: https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons@master/svg/synology.svg
        href: https://storage.${SECRET_DOMAIN}
        description: Network Storage & Backup
        ping: 10.57.57.201
        widget:
          type: diskstation
          url: https://10.57.57.201:5001
          username: "{{HOMEPAGE_VAR_SYNOLOGY_USERNAME}}"
          password: "{{HOMEPAGE_VAR_SYNOLOGY_PASSWORD}}"
          volume: volume_1

#   - Visual Studio Code:
#         icon: https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons@master/svg/vscode.svg
#         href: https://vscode.${SECRET_DOMAIN}
#         description: Code Editor
#         ping: 10.57.57.60

    - Docker Management:
        icon: https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons@master/svg/portainer.svg
        href: https://cloud.${SECRET_DOMAIN}
        description: Container Management
        ping: 192.168.57.2

    - Remote Access:
        icon: https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons@master/svg/idrac.svg
        href: https://idrac.${SECRET_DOMAIN}
        description: Dell R720 iDRAC

# ☁️ CLOUD SERVICE
- Cloud Services:
    - Traefik Cloud:
        icon: https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons@master/svg/traefik.svg
        href: https://traefik-cloud.${SECRET_DOMAIN}
        description: Cloud Reverse Proxy

    - Cloud Monitoring:
        icon: https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons@master/svg/grafana.svg
        href: http://192.168.57.2:3000
        description: Cloud Infrastructure Monitoring
        ping: 192.168.57.2
#        widget:
#          type: grafana
#          url: http://192.168.57.2:3000
#          username: admin
#          password: "{{HOMEPAGE_VAR_GRAFANA_PASSWORD}}"

    - Storage Cloud:
        icon: https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons@master/svg/minio.svg
        href: http://192.168.57.2:9001
        description: MinIO Backup Storage

# ⚙️ KUBERNETES CLUSTER
- Kubernetes:

    - Longhorn Storage:
        icon: https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons@master/svg/longhorn.svg
        href: https://longhorn.k8s.${SECRET_DOMAIN}
        description: Persistent Volume Management

    - Grafana K8s:
        icon: https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons@master/svg/grafana.svg
        href: https://grafana.k8s.${SECRET_DOMAIN}
        description: Kubernetes Monitoring

    - Prometheus:
        icon: https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons@master/svg/prometheus.svg
        href: https://prometheus.k8s.${SECRET_DOMAIN}
        description: Metrics Collection

    - Alert Manager:
        icon: https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons@master/svg/alertmanager.svg
        href: https://alertmanager.k8s.${SECRET_DOMAIN}
        description: Alert Management

# 🎬 MEDIA CENTER
- Media Center:
    - Jellyfin:
        icon: https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons@master/svg/jellyfin.svg
        href: https://jellyfin.k8s.${SECRET_DOMAIN}
        description: Media Server

    - Jellyseerr:
        icon: https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons@master/svg/jellyseerr.svg
        href: https://requests.k8s.${SECRET_DOMAIN}
        description: Media Requests

    - Prowlarr:
        icon: https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons@master/svg/prowlarr.svg
        href: https://prowlarr.k8s.${SECRET_DOMAIN}
        description: Indexer Manager

# 📺 CONTENT MANAGEMENT
- Content Management:
    - Sonarr:
        icon: https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons@master/svg/sonarr.svg
        href: https://sonarr.k8s.${SECRET_DOMAIN}
        description: TV Series Management

    - Radarr:
        icon: https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons@master/svg/radarr.svg
        href: https://radarr.k8s.${SECRET_DOMAIN}
        description: Movies Management

    - qBittorrent:
        icon: https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons@master/svg/qbittorrent.svg
        href: https://qbittorrent.k8s.${SECRET_DOMAIN}
        description: Torrent Client

# 🌐 NETWORK & MONITORING
- Network:
    - pfSense:
        icon: https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons@master/svg/pfsense.svg
        href: https://fw.${SECRET_DOMAIN}
        description: Firewall & Router
        ping: 10.57.57.1

    - WiFi Controller:
        icon: https://www.svgrepo.com/show/102795/wifi.svg
        href: https://wifi.${SECRET_DOMAIN}
        description: TP-Link Access Points
        ping: 10.57.97.143

    - Speed Test:
        icon: https://camo.githubusercontent.com/4ccc83cf6b1f06e999c378bda264433ec83994031c156a5c88876b53eb57b201/68747470733a2f2f692e696d6775722e636f6d2f61436d413672482e706e67
        href: https://speed.${SECRET_DOMAIN}
        description: Network Speed Testing
        ping: 10.57.57.62
        widget:
          type: myspeed
          url: http://10.57.57.62:5216