---
title: Dashboard
theme: dark
color: zinc
headerStyle: clean
layout:
  Infrastructure:
    style: row
    columns: 3
    icon: mdi-server
  Media:
    style: row
    columns: 3
    icon: mdi-movie
  Network:
    style: column
    icon: mdi-network
  Development:
    style: column
    icon: mdi-code-braces
quicklaunch:
  searchDescriptions: true
  hideInternetSearch: false
  showSearchSuggestions: true
  hideVisitURL: false
