# yamllint disable
kind: Secret
apiVersion: v1
type: Opaque
metadata:
  name: n8n-secret
stringData:
  #ENC[AES256_GCM,data:dDMb/v1FpE/P8g682YJFZi6oXOfS8KraZLOgUBAM7rfWyf/Eb8tmQLq47VKJoWWZ2A==,iv:h+U+2cVyj24U0VhenKnpZaCAFbU05UXjE8ULJTvxpQs=,tag:MxaWyB4MJZCb0dBXeBp0Bg==,type:comment]
  #ENC[AES256_GCM,data:O5wjzgB1Ps1KTr5RYWebjZGHaAo8u3HmAg8ykG995ZzT//Cg5u7wSxgfQ8mHB32V3aeN9g==,iv:utN4mhdcYbNXL6sLsHHM9bErTE/iAn8ElLh7FR9LjF4=,tag:Yr2Y+M9QO/FU3qXQ51+ihg==,type:comment]
  N8N_ENCRYPTION_KEY: ENC[AES256_GCM,data:ml4TU8BqZrnr0HSDXuJkKLqo6A+YiHPJTShXFKT0BxapO3Mj070a3wBNQPU=,iv:98ySvHKiDvNaAmj4SXT6shyObkqjllIwW2POKI7cWDo=,tag:QSZWDJ8DAijgD9kX0UfeoA==,type:str]
  TELEGRAM_BOT_TOKEN: ENC[AES256_GCM,data:HS//PMnL++voxNWZsfZ9xbKH3417+kNGGOQLtm2MXwherE7Cfw5v3ZoceGs1mg==,iv:wq2p5BRPL3pO+pn+lyKBTSVYLlF+F9TZLh/vUaJ/V5E=,tag:RbUElTfCwhINnwrIwlBjAg==,type:str]
  TELEGRAM_CHAT_ID: ENC[AES256_GCM,data:A9HPJg+NtzhJQg==,iv:e/o9nR1D+NoxE+c28ioV6qxZsjte3YopwQNM7Mcrp1o=,tag:L3usbjYLYv1zhaWsRDTW5w==,type:str]
  ANTHROPIC_API_KEY: ENC[AES256_GCM,data:lhq30q6CncGun6rbeAaWL1obJQgpTUEWYOSBi1Ma5uRhiLmestgFX/oINlpG7wUOU1cNBphKPg/dsC5YPCrOO+8NEovhR9RYq6xg3kS71f5mZzytFtkFEwT8j2zw0GGUfSEkkrx6JmKTD5t7,iv:zbqiCFoNst+Uxvu2eYuIT6wwXp1wKSAohpJ39Ok6Z0E=,tag:Kp0MTaT7U9UXcfN1db220w==,type:str]
  ICLOUD_USERNAME: ENC[AES256_GCM,data:reo5Pw4u8aU1sj16h1QC,iv:j8+qt1c7/AkbOKOB+RvSzdzKKZFw1/mO/ZUzzHzKrJQ=,tag:H9d9mETDy73R9xZ6qLJ8Gw==,type:str]
  ICLOUD_APP_PASSWORD: ENC[AES256_GCM,data:CmdvPI/HferYO6MMtmRzMP9ISw==,iv:kzqtXwS9zykuq5ZKgKSIhuG4VZpFEpDyIgb/GcINms4=,tag:xtZ6CncCIYCTMnKohUgq4A==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLenlpTEgzOEY2aVVpdUI3
        d1M0a0RRditPbkJLVEk2OCtTVWIwdyttR1FnCk80K1ZRRTNqeTdLbzlPUEZBZXNw
        a2pWT3Y0Y3EvaE5KUTVuL1NzbVA4bjgKLS0tIGY2c05aWGtNVno4ZlFHSUxBczRF
        eHFLa2hsaFBwS3BuTlBJb1kxWFozMFkKqzqw5XAWhNakEINscttAdlfLqZlGn4mx
        jEtKYqLD2oGImrNrEMDuMahjHUzRDm4E2oEsykfejEqv4oV4uhq67g==
        -----END AGE ENCRYPTED FILE-----
      recipient: age169tkyzjgmevv6qsm63yvmw5esv3d0mgpl85phljxw7ku235904pqg8qg3l
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-30T14:36:50Z"
  mac: ENC[AES256_GCM,data:aBU3J6tZYBEm8ukjpWcGD3JUbRdB85W11EqFy95XAgKAehomcV3TkO//nuKiI0ylzw2yeroFWLKZ6ROnBM3m4uJk9fBtPeGTLfDP8z7gcGnQJEobAFwPqAeY01UpwpubMcwTK/F7efb51M99+FJv4RnWduZfBflA3u6RNKmJmT8=,iv:89nNfzNJB+NPa/e1c0EJzrEe2+XPDQJm5proR5RFDp4=,tag:8J1WUmH4gh03remCW5csFQ==,type:str]
  mac_only_encrypted: true
  version: 3.11.0
