# yamllint disable
kind: Secret
apiVersion: v1
type: Opaque
metadata:
  name: n8n-secret
stringData:
  #ENC[AES256_GCM,data:dDMb/v1FpE/P8g682YJFZi6oXOfS8KraZLOgUBAM7rfWyf/Eb8tmQLq47VKJoWWZ2A==,iv:h+U+2cVyj24U0VhenKnpZaCAFbU05UXjE8ULJTvxpQs=,tag:MxaWyB4MJZCb0dBXeBp0Bg==,type:comment]
  #ENC[AES256_GCM,data:O5wjzgB1Ps1KTr5RYWebjZGHaAo8u3HmAg8ykG995ZzT//Cg5u7wSxgfQ8mHB32V3aeN9g==,iv:utN4mhdcYbNXL6sLsHHM9bErTE/iAn8ElLh7FR9LjF4=,tag:Yr2Y+M9QO/FU3qXQ51+ihg==,type:comment]
  N8N_ENCRYPTION_KEY: ENC[AES256_GCM,data:ml4TU8BqZrnr0HSDXuJkKLqo6A+YiHPJTShXFKT0BxapO3Mj070a3wBNQPU=,iv:98ySvHKiDvNaAmj4SXT6shyObkqjllIwW2POKI7cWDo=,tag:QSZWDJ8DAijgD9kX0UfeoA==,type:str]
  TELEGRAM_BOT_TOKEN: ENC[AES256_GCM,data:HS//PMnL++voxNWZsfZ9xbKH3417+kNGGOQLtm2MXwherE7Cfw5v3ZoceGs1mg==,iv:wq2p5BRPL3pO+pn+lyKBTSVYLlF+F9TZLh/vUaJ/V5E=,tag:RbUElTfCwhINnwrIwlBjAg==,type:str]
  TELEGRAM_CHAT_ID: ENC[AES256_GCM,data:A9HPJg+NtzhJQg==,iv:e/o9nR1D+NoxE+c28ioV6qxZsjte3YopwQNM7Mcrp1o=,tag:L3usbjYLYv1zhaWsRDTW5w==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLenlpTEgzOEY2aVVpdUI3
        d1M0a0RRditPbkJLVEk2OCtTVWIwdyttR1FnCk80K1ZRRTNqeTdLbzlPUEZBZXNw
        a2pWT3Y0Y3EvaE5KUTVuL1NzbVA4bjgKLS0tIGY2c05aWGtNVno4ZlFHSUxBczRF
        eHFLa2hsaFBwS3BuTlBJb1kxWFozMFkKqzqw5XAWhNakEINscttAdlfLqZlGn4mx
        jEtKYqLD2oGImrNrEMDuMahjHUzRDm4E2oEsykfejEqv4oV4uhq67g==
        -----END AGE ENCRYPTED FILE-----
      recipient: age169tkyzjgmevv6qsm63yvmw5esv3d0mgpl85phljxw7ku235904pqg8qg3l
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-30T11:49:36Z"
  mac: ENC[AES256_GCM,data:lBzUKvpCTHOYTLZ2qaDE8QQgZ9pycRT+Ls5sUrn7/9/WyNvUm8SR+Ld/PObABeeuwlLgcx/9Sx4GXgkICqgykXwqlmbFTrGRxnNYRn9aPVDixLxI7XeSMRDlCfHgfLFer3x4e1LUdF0Vp9iKhU6b4mt0TmCyCRmGnaBrQRl9Q+Q=,iv:faUrLsGY4eU1x+xEiEqtj83adHG3updRnnqxzspOzeU=,tag:2vRBRyQ85fFTdeUTR88Ing==,type:str]
  mac_only_encrypted: true
  version: 3.11.0
