# yamllint disable
kind: Secret
apiVersion: v1
type: Opaque
metadata:
  name: n8n-secret
stringData:
  #ENC[AES256_GCM,data:Q05vcC5HUGXXLSDR5IKGlJ6VyQv5pUwps8EoHpsIZ9pKWS0i6SxAhi9LSYYc118Pbw==,iv:M0+M8A9ZElFRECZ1BMWqp6y4h4wr8WT2biokRjOyJj4=,tag:vkmFhHmxXKDT0ssHcfWVKA==,type:comment]
  #ENC[AES256_GCM,data:xZOPc2/oXNv3px0cGvhj3sdX6EjK8AztFvLRnmiiUgNv5KU4Sx6YIS3mj2bFiR57yPJ+6Q==,iv:7pSmcw/uumdiOechLmBr4nPdrqOR7Cbq7qBC7u4z8G4=,tag:8fQUMQtNGlO0NKrU9UokAQ==,type:comment]
  N8N_ENCRYPTION_KEY: ENC[AES256_GCM,data:SkvlwgYGEThvsNLnSspr4SDHI4z47OZTFIDBOASiZtt3MVI0qZcfr7xfjaQ=,iv:WRt0NoSZotVh80Kkze0SUuQth4CGhrRbhWxemtg/LMo=,tag:rJa22q2a6jxDs3DFcfxN1Q==,type:str]
  TELEGRAM_BOT_TOKEN: ENC[AES256_GCM,data:K+Lszx6wU9bm4YalZCwCceh2dTpbDK77Sc/8wioQKytemAzyT0Wl9LCb+Oi7nQ==,iv:Maen185k2Qh4ASR8BEZvcDIpbXK209akLe8cp7+oP2s=,tag:VSQc1ES/DW56dejguKHVjQ==,type:str]
  TELEGRAM_CHAT_ID: ENC[AES256_GCM,data:5zAxAghXY+sI9g==,iv:9ywNVsax4Skx8dj+7TA2WZuzIZU5XidlBk8wUmH+Nks=,tag:LIFpgJ+MBgIUilDfsD94zw==,type:str]
  ANTHROPIC_API_KEY: ENC[AES256_GCM,data:ZMWMdPg/yDAOLxNOlJp4jVina7RCmez/kT1TNolcMg2UyyLnrKWorOtfT6tm+hrUKnwnZw8+TVlyw5b1pfSfJPjx5cACsQbOtWSRc8Oq13g9o+M2hQyVCyFsGBu2Zk+7XMWDjMody002BzEJ,iv:/Zc+bLwCP0FpHSagWIlWaea3LQyfUmqYoDiYkGKUtzc=,tag:mkquAHsB7GfawkYduJpXNA==,type:str]
  ICLOUD_USERNAME: ENC[AES256_GCM,data:8hHg5C9obmmwl4VxP2u7,iv:UsQfrw6QyhES3an36+SChlkxsphoQjkkrhiXAJi6QoA=,tag:SsklEmIpeSSUsWFq9x+cFA==,type:str]
  ICLOUD_APP_PASSWORD: ENC[AES256_GCM,data:iITk9TQspPQYGf0DRF4DQNQuZQ==,iv:ohtlvYv1IqHmC38htDL+KYiXW8GYjYHZoFNh5+XoSEo=,tag:eOvTuuhSeWwxIcas7W208w==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1dHZYVVd3cFRwNUxtZGVi
        L2h6cWYrbW9kYmQwdExBaDMyN2NWdDQyeVRrCjV1cWJuTGpCUmQ0OFZJWEpDem92
        QkU3NDdZRXQxeUtObmlBdURFRmlWQUEKLS0tIDZtRkhIY1hSYnFYbjliY0lyRDV2
        NVcrdHNudWJBeHBySXZwL05UNnVMQ1UKr9zT5lJYaXgvWaT/FEHekJnVhwjM0tAR
        vpXOr56L9AvJNF8l4eSsrQPIDk4T8cqL73dpQNqkuMnw905+NlVZ6g==
        -----END AGE ENCRYPTED FILE-----
      recipient: age169tkyzjgmevv6qsm63yvmw5esv3d0mgpl85phljxw7ku235904pqg8qg3l
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-03T09:43:08Z"
  mac: ENC[AES256_GCM,data:QmSJ3+EY9SWya6ShpkqqW6M0fGfTv7KdPxqK6QYneMubfPQCckZy4g6QeHEdGoNwYAP/Aa4FPc07/yGtBQya6OsP7JONx6c1DRO5z142Vg0UduuNAIsx5WFaskRfoHd9ch/X8BJx1gRYhtGBiKxInR3Bb4EnA2++epsxTKOKl3c=,iv:VhP3Ev/Sop8R2HpHaO6TARvD/PZ2BBr4cPtDReOtQ4U=,tag:wzwvatrJRAL3LrQpXvCpBg==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
