# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:F3j50dEjnhSJtJFTwDhTtsqotSW3vSq6MY3Sfmn++iFgI9oYy4yi26ecW1mOh2ZWeLFYpEI=,iv:xSfHEw6DA3Owcq9LXA0stLLFB3Y29jUsGi/lwr/xEO8=,tag:u3bfmCPYVkJp/Zp8mGePUw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3UDZyMUZxcVA2V0lSUHY0
        dkc2WmJSK2ZiaXRXRWp0WmVRK0tsQ0ZNdENvCkpGRDg3WDFOMlZlU0RiYWtzN0tX
        dmgxTksrT25zLzVQMUQ3d21BOHdncWsKLS0tIHVVWE14TitpemRuOTZodXNyRmZH
        WjF6RHZKVTRJN2N4NUFMUWczcS8rRVkKXZfy4X0EGhEx8tUnAd+dlOsnuzezakWx
        Yk7ysaE9PFoa43ln20UAh4uguuEKdqP4dNYte4hHXU7etrAlM4ahqQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age169tkyzjgmevv6qsm63yvmw5esv3d0mgpl85phljxw7ku235904pqg8qg3l
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-05T08:53:40Z"
  mac: ENC[AES256_GCM,data:8bXOCcFX7gB9l7U3jg9K1b9pvHdvUNgXGyvMxW2HGJg9JQogIFxJjTSinccWOwo1lyOcvAnPhYW3a+Pu0Qay0ZPzgvFCHsZ4eHZ7WfUOMaX3msTCF87rZo64Un2/iuM1h1sgLuiImQLr5kUriWTT+55X1aaRrxNB6SvWsR83bss=,iv:vU+qm4OCd55h0CfbPuTZNNj3L0sKT9O5OEG6qPSZqYw=,tag:rvIi+lfr2WyGu3QUkvT9vg==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
