# yamllint disable
kind: Secret
apiVersion: v1
type: Opaque
metadata:
  name: pve-exporter-secret
stringData:
  #ENC[AES256_GCM,data:eBkG0ci4+vsQVwZG5S2sgqEJucF4/DXKaUit6nFwbtAG++f3vvYUPVJTAwRA7AkoLHa5sxQM6xr/zAbmE06trUtjjhjspQ==,iv:NteenDK9Za80hAuiIWLNgfwzH6rRCmqhLv07rZrCPOE=,tag:01F2iEq+bJvLn3c3MsiD/A==,type:comment]
  #ENC[AES256_GCM,data:GFHnpKb4Sw1+WGz4taw3THLz33JFPcWVp2b1ZG2NfBsLf96S/ilFVKz00muW2UU0muxMPfGKsrY6H2wlYmtP9vrHbbTiGbs=,iv:TnJMqaxK0UDHxiUQr8DLX8OQIW3y6XeZZBObIxgv20Y=,tag:g6/1Jv+SS2ZrtaHqXraNkg==,type:comment]
  #ENC[AES256_GCM,data:tp5AL0Tfk+Rq+LyGER6Nb/E7Hw2X7LmEbrt1QrLwe6bZDwzhbpHcNR2BoIZ2FKckQM+Yh+ZaJ3ZBzwiu2s5LEj9rlQ==,iv:URtQrQSCSE6a6+Rebed3fM7MFZbDWSnB8EsItPxiW+4=,tag:XksRK3kdXI9f4Jr0vQleSg==,type:comment]
  #ENC[AES256_GCM,data:rAkWz2M+OMNvm+87icBA4Jv2jsfp/JfcoslLpqKvG3cnSTWkd44kxdEMRxBiMkvw,iv:6A8AQhBIl84eusdeFFZaPgV5DkMdF80gfAmTBTyWDrQ=,tag:mCAXHoVqFJeMo7cLReNrtQ==,type:comment]
  pve.yml: ENC[AES256_GCM,data:dZ2jqTJ6F77HytQ7R9Q6ol8kqsqpsvnXKi/bMW+bZJiFj2VDGgryeqFZ4/g08EBiG+hyaPCsywch5771f52iS8VpGs+1VhujA0fxF9fFVxTHQOG0lHL1YbpUPoyE5h2rR6fRaX0kGyl08YeYeATXt9mQAeHVcEH6WUBQ/Z54WVu57uaENG/JwQyK5IwEaqY0j1qYEPomQruFR9tBulAdjqgdzeCuF/cbvSXCQXEEEyOk1b+L0x0ZSXP9eEwoHXU1uqIVTmwYBgqaIHDkYM+iVMTbW2tXKtl+8rPoSvEn+t4TLi9vNCbRuhhbrNtCtlDrKfFhnF3+dg/7K/wmSepxnSP9Ig8NHlw/zYtPawf77rGq5skWLjEDJUhrfid5dfIp2uasm1fQfRFLRVliO4oErCUYtlWhAZjtSd3nt6/4buqr1BvMzC2K5ISVEfKVFDEub8p3wVOsT9LOdjvVxx92omWlcLoI8FYXIP49bVNdfIqYJ3jmdfTMSJwtRinvhLDHxZyI9gHai1WShpHomCP3Y3fz36SHBn8L4zMNkde88YlII3r3hyU60eP4y3p0iIL6cdBfpJ6qZfmuMoqoPOfXMg+DCecsEp5vm9nNjuVeZSLmpi5/6zIqVUm84bdjpDLJHdgZ+dKUemSMatzhBSyfHekqm0EvEockzxaXQeiMlOrmSRZT/SWVRCyyyhOE6QXubo1EQLOhPYp0mcgnZ4bZv0/f3OB3MQ==,iv:viWH/YlMZDhj90okbFQCytAe81+16PWwRpC1fsOv4aY=,tag:DSw5Bn/8VKr2vukdGXVP5A==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0MmdiT2dSZVcwTXlsejRx
        a3NkRlJtb2drQTU1Z2pSMHBMYUZQVTc4d2owCmhXTURYWjMzMzFQMU8vd2NFS09u
        YjlkVWtqblZqaENkdVN0dlR3SUg5Q28KLS0tIHBEeVd1VXhpZUlPQmV5eGl0SFdt
        U0VyN1dUaWhRek52UHUrU1lnRkppUDgKXSrVUDdF02SAze/iNLh76qS9qdREzbCc
        DLbSOw9dEseXHpnpYta+b/huTd2MVY4GUw5O2CMcRmI1BOxORhoUSw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age169tkyzjgmevv6qsm63yvmw5esv3d0mgpl85phljxw7ku235904pqg8qg3l
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-11T06:59:04Z"
  mac: ENC[AES256_GCM,data:54t6pmR8Ym+A96QfVKfgbliSgMyEcJYlJJxR73rD2HYLRGHmIYbSc7ZFAPUUYxjFHP3LsrkhljyBzn+mOwSghJf3SSMDH2F4drVue+fvNsCMB8rUxspBWxD04u0IDV54ZoX2c4cwun3UccmP2z2XySERNgdAAVG1v2od4Rxb0hk=,iv:TE5rBfthbsPhn8Ebv/eGwwJXt93/QRojnluSEgyLtKg=,tag:SOI9Sdcrka2J5E8LBHFmYA==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
