# yamllint disable
kind: Secret
apiVersion: v1
type: Opaque
metadata:
  name: pve-exporter-secret
stringData:
  #ENC[AES256_GCM,data:eBkG0ci4+vsQVwZG5S2sgqEJucF4/DXKaUit6nFwbtAG++f3vvYUPVJTAwRA7AkoLHa5sxQM6xr/zAbmE06trUtjjhjspQ==,iv:NteenDK9Za80hAuiIWLNgfwzH6rRCmqhLv07rZrCPOE=,tag:01F2iEq+bJvLn3c3MsiD/A==,type:comment]
  #ENC[AES256_GCM,data:GFHnpKb4Sw1+WGz4taw3THLz33JFPcWVp2b1ZG2NfBsLf96S/ilFVKz00muW2UU0muxMPfGKsrY6H2wlYmtP9vrHbbTiGbs=,iv:TnJMqaxK0UDHxiUQr8DLX8OQIW3y6XeZZBObIxgv20Y=,tag:g6/1Jv+SS2ZrtaHqXraNkg==,type:comment]
  #ENC[AES256_GCM,data:tp5AL0Tfk+Rq+LyGER6Nb/E7Hw2X7LmEbrt1QrLwe6bZDwzhbpHcNR2BoIZ2FKckQM+Yh+ZaJ3ZBzwiu2s5LEj9rlQ==,iv:URtQrQSCSE6a6+Rebed3fM7MFZbDWSnB8EsItPxiW+4=,tag:XksRK3kdXI9f4Jr0vQleSg==,type:comment]
  #ENC[AES256_GCM,data:rAkWz2M+OMNvm+87icBA4Jv2jsfp/JfcoslLpqKvG3cnSTWkd44kxdEMRxBiMkvw,iv:6A8AQhBIl84eusdeFFZaPgV5DkMdF80gfAmTBTyWDrQ=,tag:mCAXHoVqFJeMo7cLReNrtQ==,type:comment]
  pve.yml: ENC[AES256_GCM,data:Y8Mnb0/2J8uNryiQyWWGqBhZ7vfwro8/sAagINnCI2G7FJamo/OYDWEMpO+MJ6p8vyTNGttp3kkO9EzywQXtruARukPkTq138HLyVk+Py7NRywoHq/bHOdB4/6O7Gxv6+jm5JPXmGpfYHXu9f4dAcoBKz+2B1XlEUNyiBPBq6k11GeAYKkIfzxAXfGXs93nzZmX3PWMUCtO1Fz4IPMdTBg2X8Oaya7ucDKn6A97nX0bQehkquOMQPZO/KB94H/EaSyyZCbdwbVQdMuycjaroPOe8uD8GfhJDXvdD6wbj+UKtTihRiPmwmSticwKehqQo7TAxdQ9ZwKWtvD2rYil1Wlmct3gRZ/31/VuGsN9c2C69tfYKTpAvxVA+ZRRgLLbJ1YacluKIjXoQw4TYd9xR6eQ7U2/JzAdWZlR2vcHFH0rPQcWaBxUciXPtnXOg+IYkq7fG1lola/xpSr0iZkqLoTnfXewXFIOqswowu+Du8w4C43r5t5H55GCBKxl7,iv:QQ4TPtvhb3hrtRTJoKVy6QUMHZRo9xbJoq/nt47y8uE=,tag:mTddAQrT6ncb87+RB8SqdA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0MmdiT2dSZVcwTXlsejRx
        a3NkRlJtb2drQTU1Z2pSMHBMYUZQVTc4d2owCmhXTURYWjMzMzFQMU8vd2NFS09u
        YjlkVWtqblZqaENkdVN0dlR3SUg5Q28KLS0tIHBEeVd1VXhpZUlPQmV5eGl0SFdt
        U0VyN1dUaWhRek52UHUrU1lnRkppUDgKXSrVUDdF02SAze/iNLh76qS9qdREzbCc
        DLbSOw9dEseXHpnpYta+b/huTd2MVY4GUw5O2CMcRmI1BOxORhoUSw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age169tkyzjgmevv6qsm63yvmw5esv3d0mgpl85phljxw7ku235904pqg8qg3l
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-10-02T16:21:32Z"
  mac: ENC[AES256_GCM,data:zCIZDBrdO82HeuGJT/qp/n+Fw6OLQxpgUFOCvcbl6Gksem8IlhBNoS9n2WI/Ffzs5EXbRKvWD+DrMJZ/ODLLMx49Fy1SoMWi0vRKL9bULRDFAOLbqIUhP34OsmpKExDquS8OoreUb0xhucfNZOoYO8vCf5Dh9ctH0EeILDpGuyY=,iv:DE6X0bDiEDUPXjc0m266X/c1gIqlfCp90oF/cA7JDRQ=,tag:YKSQ45W0WVm1lFjxDIvIZQ==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
