# yamllint disable
kind: Secret
apiVersion: v1
type: Opaque
metadata:
  name: pve-exporter-secret
stringData:
  #ENC[AES256_GCM,data:eBkG0ci4+vsQVwZG5S2sgqEJucF4/DXKaUit6nFwbtAG++f3vvYUPVJTAwRA7AkoLHa5sxQM6xr/zAbmE06trUtjjhjspQ==,iv:NteenDK9Za80hAuiIWLNgfwzH6rRCmqhLv07rZrCPOE=,tag:01F2iEq+bJvLn3c3MsiD/A==,type:comment]
  #ENC[AES256_GCM,data:GFHnpKb4Sw1+WGz4taw3THLz33JFPcWVp2b1ZG2NfBsLf96S/ilFVKz00muW2UU0muxMPfGKsrY6H2wlYmtP9vrHbbTiGbs=,iv:TnJMqaxK0UDHxiUQr8DLX8OQIW3y6XeZZBObIxgv20Y=,tag:g6/1Jv+SS2ZrtaHqXraNkg==,type:comment]
  #ENC[AES256_GCM,data:tp5AL0Tfk+Rq+LyGER6Nb/E7Hw2X7LmEbrt1QrLwe6bZDwzhbpHcNR2BoIZ2FKckQM+Yh+ZaJ3ZBzwiu2s5LEj9rlQ==,iv:URtQrQSCSE6a6+Rebed3fM7MFZbDWSnB8EsItPxiW+4=,tag:XksRK3kdXI9f4Jr0vQleSg==,type:comment]
  #ENC[AES256_GCM,data:rAkWz2M+OMNvm+87icBA4Jv2jsfp/JfcoslLpqKvG3cnSTWkd44kxdEMRxBiMkvw,iv:6A8AQhBIl84eusdeFFZaPgV5DkMdF80gfAmTBTyWDrQ=,tag:mCAXHoVqFJeMo7cLReNrtQ==,type:comment]
  pve.yml: ENC[AES256_GCM,data:NaosDtrATcjYjZtc/omoURM0TxC4bu8b7kKAQy2MdusHAzuntbxqRBLjoLjSpkhfexPqpz5s9ZBO6qOTJ4t/t+O76lgKYRQmlNX6ry4S1MTe2o9WpKzpKqdgBk9ViqbrR5wt7u+TsqRMpcb6HlbKo5chiMYWEo3EiwXuDT035dVSn2zidSk1YIrHgzb1Z1Z5mXKU+qFy5f78fRzlSwJ4gJWx4A2CethMMlWpWCYzl7QANXE9ezKAYn5Wixb5cGf1NCshzK0iAGCzN0hMjfeD4qSsPfYRcVMXB9oBnwAUsz80L7l8ZEyD3Awhi4yCpAFFyadMzT+eseO4sDz7p5ddnNYt4osEHNGziHqdqjir9qGxeIY=,iv:kRNi5VAc8PkKXg1j7+Gne8MCnimw4ERDSzFC7vaoUAQ=,tag:KY/T1t+5UMC1hgWbw1ljqA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0MmdiT2dSZVcwTXlsejRx
        a3NkRlJtb2drQTU1Z2pSMHBMYUZQVTc4d2owCmhXTURYWjMzMzFQMU8vd2NFS09u
        YjlkVWtqblZqaENkdVN0dlR3SUg5Q28KLS0tIHBEeVd1VXhpZUlPQmV5eGl0SFdt
        U0VyN1dUaWhRek52UHUrU1lnRkppUDgKXSrVUDdF02SAze/iNLh76qS9qdREzbCc
        DLbSOw9dEseXHpnpYta+b/huTd2MVY4GUw5O2CMcRmI1BOxORhoUSw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age169tkyzjgmevv6qsm63yvmw5esv3d0mgpl85phljxw7ku235904pqg8qg3l
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-03T12:09:58Z"
  mac: ENC[AES256_GCM,data:ifiX/cN2KDlSSs4rSkd7gd4+eiY4LUGIOfn7qdXk8sPb4C/wzjx6ssaQQbgue1BIQOAqzmVRu/HyBUq9PTPMKkUiicWVAAIRVm5FDZHo5utC0qxUMtYW9dJdykUQ1xncjQo8tBrA445bj42rQjIeRInvWXE0vCrim3+ibPF0PAU=,iv:YcSipSolj3QaKlsz2YppsJZ+c+TOqWJGqAZOjKiotng=,tag:oor19k7i2ZBcIgcjxOrE0Q==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
