kind: Secret
apiVersion: v1
type: Opaque
metadata:
  name: filebrowser-secret
stringData:
  FILEBROWSER_ADMIN_PASSWORD: ENC[AES256_GCM,data:sNAj7t4QcTx1iIRRRApjW7amdzE=,iv:IQErskTObpIle9EghltdtJQkLtuXoxhi6jeUFYGxWpg=,tag:EYeQzVLA+o+g3cCw2MAn5A==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3OE1hd3JxZjFnc3BrRnJ4
        MEtHTTl0cjdWdnd1WlovOStCTSttajVsamh3CkpZWFVsQTI2UjFLM0x6V24zdll3
        RXJGK01ZUllOVVY5dTY0bGc5cEdPdW8KLS0tIEpYeGJmZEFmZkFFeGZSSDNtSXpF
        T0pTSjdsalNwcnl5aUliMVdTcUpsZkkKi2ggpiIziZk90jVvK32tfS9MhSS7wp3O
        E/7LPF9uG6clsscqoG4kvhBgImHsuhFMb81Yy1ORDbYbFGAEQnVMoQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age169tkyzjgmevv6qsm63yvmw5esv3d0mgpl85phljxw7ku235904pqg8qg3l
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-22T17:52:46Z"
  mac: ENC[AES256_GCM,data:TUzySIaprvOnJlU3afmtxd4TgItR5Mdrz91MysMl8iaw8Efs+MWB1JaqRikEIlMbjwCfZRhFYDx9ftb4NR3SjYpbQxRIwTm095z1sKzh/mmsB8oex3m4e9xO1gBzGQHDMgi3dcmAKXIBSJFxCjo1yWzEWZE13yEFpC51cs5Izrc=,iv:05CvYfwp5yHh0qadRuamNLtY/4ttivtZNoyJYpvc2eo=,tag:cE3vh1x1Y5DALcBBryGzbQ==,type:str]
  mac_only_encrypted: true
  version: 3.13.2
