apiVersion: v1
kind: Secret
metadata:
  name: emag-watch-telegram
type: Opaque
stringData:
  token: ENC[AES256_GCM,data:5jEs8BaJj5uQ3Se/zB9OKzADXv88UzXxjZGIDUHf33R9tJZRX4rOB5mjDmfVwQ==,iv:N8zxlTq1776QUi06EQaT++aXG59e0PVUN0fOak5a1W0=,tag:9KYBA9naEAaH/HebEF5Rrg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjYUVhR2RWQlVRcFc5NUZ3
        U3IxK2lZemdra1ozNjg4K1F1Y1lLODdDRVhVCmhET1Z1QnpvZ21aaDhqVTJLaU9M
        V2wxbTREVklXMUhQMThpOFd6TkdlSkEKLS0tIHFIUng1c2VlOVZYa0p0cFpPMW9v
        WXUxWS94Y1dMaVZSQTdhQjBPTnpGeXcKFpHLN7Of7X5LVKgEKevFFATIf6Jg+Mt+
        BCMPr4GnP24KKlQBIWlfmBjlLi4EZF5HJKK5/19YcQjagwwlDJkLlg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age169tkyzjgmevv6qsm63yvmw5esv3d0mgpl85phljxw7ku235904pqg8qg3l
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-10-06T10:24:02Z"
  mac: ENC[AES256_GCM,data:JhAcQJZ0ECyWkCqGLwm9upPVnQLYSXhUMJg1qgY8KuhooADqxTKKFfwLUUbLWB8Z5al0OGggOG05FUBpuVr5IFjFJ9eiGbRZG0RpTokmA8hpUkwlzTdbaMAykfcQ7kgWxcfdff95J2TyARSeWhBYZavDtQzGeEoEaYGVHDbELnU=,iv:3XhQK95QxnGZqERLhoc/+i2cBYgWMniC1zUC9Fjg5Yw=,tag:3n2/wIGLqLKN/50bjFdmWg==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
