---
- name: Detect Tailscale IP address
  shell: ip -4 addr show tailscale0 | grep inet | awk '{print $2}' | cut -d/ -f1
  register: tailscale_ip_result
  changed_when: false
  failed_when: tailscale_ip_result.stdout == ""

- name: Set Tailscale IP as fact
  set_fact:
    tailscale_ip: "{{ tailscale_ip_result.stdout }}"

- name: Display detected Tailscale IP
  debug:
    msg: "Detected Tailscale IP: {{ tailscale_ip }}"

- name: Create Pi-hole directory structure
  file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
  become: yes
  loop:
    - "{{ pihole_docker_dir }}"
    - "{{ pihole_docker_dir }}/etc-pihole"
    - "{{ pihole_docker_dir }}/etc-dnsmasq.d"

- name: Deploy Pi-hole .env file
  template:
    src: pihole.env.j2
    dest: "{{ pihole_docker_dir }}/.env"
    mode: '0600'
  no_log: true
  notify: Restart pihole

- name: Deploy Pi-hole docker-compose.yml
  template:
    src: docker-compose.yml.j2
    dest: "{{ pihole_docker_dir }}/docker-compose.yml"
    mode: '0644'
  notify: Restart pihole

- name: Start Pi-hole container (initial)
  community.docker.docker_compose_v2:
    project_src: "{{ pihole_docker_dir }}"
    state: present

- name: Wait for Pi-hole to be ready
  wait_for:
    port: 53
    host: "{{ pihole_container_ip }}"
    delay: 10
    timeout: 60

- name: Enable etc_dnsmasq_d in pihole.toml
  community.docker.docker_container_exec:
    container: pihole
    command: pihole-FTL --config misc.etc_dnsmasq_d true

- name: Create custom DNS records in dnsmasq.d (Ansible managed)
  template:
    src: 99-ansible-custom-dns.conf.j2
    dest: "{{ pihole_docker_dir }}/etc-dnsmasq.d/99-ansible-custom-dns.conf"
    mode: '0644'
  register: pihole_custom_dns

- name: Restart Pi-hole DNS to load custom records
  community.docker.docker_container_exec:
    container: pihole
    command: /usr/local/bin/pihole restartdns

- name: Create Traefik dynamic config with Pi-hole
  template:
    src: traefik-pihole-config.yml.j2
    dest: /srv/docker/traefik/config/pihole.yml
    mode: '0644'
  notify: Reload traefik

- name: Display Pi-hole access information
  debug:
    msg:
      - "Pi-hole deployed successfully!"
      - "Web Interface: https://{{ pihole_domain }}/admin"
      - "Tailscale IP: {{ tailscale_ip }}"
      - "Container IP: {{ pihole_container_ip }}"
      - "DNS Server: {{ pihole_container_ip }}:53"
      - "Local DNS records added in dnsmasq.d for:"
      - "  - traefik.cloud.merox.dev -> {{ tailscale_ip }}"
      - "  - pihole.cloud.merox.dev -> {{ tailscale_ip }}"
