---
- name: Complete VPS Setup - Infrastructure & Services
  hosts: vps_servers
  become: yes
  gather_facts: yes

  pre_tasks:
    - name: Display starting message
      ansible.builtin.debug:
        msg: "🚀 Starting complete setup for {{ inventory_hostname }}"

  roles:
    - role: initial_setup
      tags: ['initial_setup', 'infra']

    - role: docker_setup
      tags: ['docker', 'infra']

    - role: tailscale_exit_node
      tags: ['tailscale', 'vpn']

    - role: pihole_prereqs
      tags: ['pihole', 'dns', 'prereqs']

    - role: traefik_setup
      tags: ['traefik', 'proxy', 'services']

    - role: pihole_setup
      tags: ['pihole', 'dns', 'services']

    - role: portainer_setup
      tags: ['portainer', 'management', 'services']

    - role: homepage_setup
      tags: ['homepage', 'dashboard', 'services']

    - role: netdata_setup
      tags: ['netdata', 'monitoring', 'services']

    - role: beszel_setup
      tags: ['beszel', 'monitoring', 'services']

    - role: dozzle_setup
      tags: ['dozzle', 'logging', 'services']

    - role: nextcloud_setup
      tags: ['nextcloud', 'storage', 'services']

  post_tasks:
    - name: Display completion message
      ansible.builtin.debug:
        msg: "✅ Complete setup finished successfully for {{ inventory_hostname }}"

    - name: Display installed versions
      ansible.builtin.debug:
        msg:
          - "System: {{ ansible_distribution }} {{ ansible_distribution_version }}"
          - "Docker: Installed ✓"
          - "Tailscale: Installed ✓"
          - "Traefik: Deployed ✓"
          - "Pi-hole: Deployed ✓"
          - "Portainer: Deployed ✓"
          - "Homepage: Deployed ✓"
          - "Netdata: Deployed ✓"
          - "Beszel: Deployed ✓"
          - "Dozzle: Deployed ✓"
          - "Nextcloud: Deployed ✓"
