---
- name: Update and Upgrade Systems
  hosts: vps_servers
  become: yes
  gather_facts: yes
  tasks:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: yes
        cache_valid_time: 3600
      tags: ['update']

    - name: Upgrade all packages
      ansible.builtin.apt:
        upgrade: dist
        autoremove: yes
        autoclean: yes
      tags: ['upgrade']
