# yaml-language-server: $schema=https://json.schemastore.org/kubernetes-definitions.json
# NOTE: Fill AUTHENTIK_TOKEN with the token from Authentik UI
# (Admin → Outposts → k8s-outpost → View Deployment Info → token)
# then run: sops --encrypt --in-place kubernetes/apps/default/authentik-outpost/app/secret.sops.yaml
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: authentik-outpost-secret
stringData:
  AUTHENTIK_TOKEN: ENC[AES256_GCM,data:nRfLNWso23WzzbPuhI2My0zqFehrMG6HwZEnOcxl9MCCFu9nq44kzSqDmClTub1BM31C/msL/Dlw+ejj,iv:S7dobEGvgPA5Za2orUxXXtph6fecTphSLhti7VJOy6U=,tag:2D/4mfD0HCvLKZ8/ZkKWDQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFMVhhb2pGVHpqUEpPdW53
        WEZ6d1VBRWFnSkdvODVROGFhODFGY1RUNzFvClVSSCtqTENtdldSNWY5eS81WGxC
        VER0c2hVSk0zVW9zY2dZbVJzQkZnNFkKLS0tIFNNanp4U2lnQmhlcmIrUms2UHhl
        WG4yTElIalNERGt4RGVtcHlMSVZma0kKOOLVgtDPEDzPxPf2gnbXH99pBHfCY5Eu
        WSx/qwizEK5arZQg5gkVkmT2TlOQF80ZbUftqhcPfIHp4ksEYViPkg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age169tkyzjgmevv6qsm63yvmw5esv3d0mgpl85phljxw7ku235904pqg8qg3l
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-19T11:10:08Z"
  mac: ENC[AES256_GCM,data:fGjM83U//BUcPOVgAp3VRzq8n3sX7XQe5ZBRn9btf70eSdzC1ISl3MNmsey0gPRhId01trIELzgTfCOd6QgZURGN0ZMgyOfcMFSZzL6yfRVB4qunslvC5U1fFWSRpQ6NQnc07eodOqY+24yMTHeCt43J+7UnhEJl45w4lXBTCRQ=,iv:9K1YnQYziDDCeeBF4TjbBcSZwwkhu/HvFXKMzmER61A=,tag:+5xMcwMJ2szD9BO6rxu15A==,type:str]
  mac_only_encrypted: true
  version: 3.13.1
