apiVersion: v1
kind: Secret
metadata:
  name: discord-webhook
type: Opaque
stringData:
  address: ENC[AES256_GCM,data:1j95PPzpcjF5PAbKwg3NEbATwXhzPo5eMu4f8bRVlkwlTI7eh8Bv7CazTVHuwwnj/8JSCYrKZb/MlRunyS89QPHlsQH/hV9AHTlODFLfcofktIjYrzoAH7X5vyQ+SQoqIr+jbhjaSErafQWx1L2oCQ7jB4o4PPnr4Q==,iv:LqxYqPPZtjPZxHkU76OTinOGKvEu4wpmQXMxIKB159A=,tag:GEnmW9Uwt2dcMjV1rLot7A==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXc0lYc0ZDQ3hvanpraDV6
        dFQzVm5jeVBLRzFacStmaHFmeXJ2QTJ3N21FCjFLMndZcFpYeHRnbE1ySFVUSnZX
        Zm9UYTZEWGx0eGdraCtjMTdmbVBQK1UKLS0tIFN4S3lEWVhPNnJYR1ZOUVE1UjE3
        cWNQNy94NzBES2xYWU45RHJpWFc4aFEK2Y7aeYuyslSJOxqQYHm7I5Zv8bv4VJgR
        d1LexRe+4yJV/7OyWKrqD64PNRbtoopXdQOXbFfPBEielvKQbM/p4w==
        -----END AGE ENCRYPTED FILE-----
      recipient: age169tkyzjgmevv6qsm63yvmw5esv3d0mgpl85phljxw7ku235904pqg8qg3l
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-25T19:00:42Z"
  mac: ENC[AES256_GCM,data:GlleLuIgqud7Iibg0bsbFuwnB4gacQ71Om9WHrisJWu1R1WXv4LY1p9c6knw7lBYXDYt9NHotpzaR/F+mqXeZMRsSViu+DeqPkwRQWD0rVc0bwi3xkrk9JIiW9v5HlfUFWZXBHTiIvafQ8ibEAC18gDzWdwOYiRbOlcmg0SRQPY=,iv:24aEbv/YdIQ0984vx4m7xKdk1E2X8rpDHaW80T5Rmqw=,tag:GXiK3G1hZtJfauECf4QKcw==,type:str]
  mac_only_encrypted: true
  version: 3.13.2
