apiVersion: v1
kind: Secret
metadata:
  name: n8n-webhook-secret
type: Opaque
stringData:
  token: ENC[AES256_GCM,data:kBXcnAi0suKJPgnqrOuQ4QgYm3ntIiJVMvJj5HU4kvZMoW52mWqejrm5U5rvN0XCA+NuBPwZ8oAqXkflxNQwig==,iv:bebOtM+nzKB0Blm9au5D1Gdb6sVHD2iR7z57eYI6IQ4=,tag:3ihPsYOcX4BDB8SeIpVvgw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOY0t3OTdoZlRyWjVFT0FJ
        WmwydDhPMm94UTUzQmVLVWRpdXl6cGVVUDJnClpaNjl1dXlteExZeng2NG9PUGYz
        aEhHc2UzSDZWb1UxSG1WZkxaOTg0alkKLS0tIDJkb3hoY2d1UGpTSk5BWXI0VUVR
        QTY2eVB4ckpaT2cyRVkyUFM5M056SVEKQQZLVOdcVau2Aj+vpX01UbNK/BtTa5hi
        nbslpqQZ7DtFvEbhszaXhxXk/zje3FP/UyJPQLKb2NXXgNLXC2cV1w==
        -----END AGE ENCRYPTED FILE-----
      recipient: age169tkyzjgmevv6qsm63yvmw5esv3d0mgpl85phljxw7ku235904pqg8qg3l
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-30T13:18:33Z"
  mac: ENC[AES256_GCM,data:EWSzJfh7LyGH/NsDTbAbY1tY0Jy/3mKOq8246rmuDKslZNnIAk7uvsQyJf9BZAj8BEx8n+Lg1NnZsYl6hGexEkrJQfcLQoBFSJX2Hnme9bN+pcLw7AmZ0z7Lpu+JC5yabBxAIXUoRIw5VZvGk6oU82sxqezUg8cwh3/jSqIECJU=,iv:2DeO3FCNIx+qFYdd/LmB8cFNBi9XYl2EsRgM0OEDZug=,tag:8Uon0TbU2ucLffAEoZ6WzA==,type:str]
  mac_only_encrypted: true
  version: 3.13.2
