---
apiVersion: notification.toolkit.fluxcd.io/v1beta3
kind: Provider
metadata:
  name: n8n
spec:
  type: generic
  address: http://n8n.default.svc.cluster.local:8080/webhook/flux
  secretRef:
    name: n8n-webhook-secret
