apiVersion: v1
kind: Secret
metadata:
  name: telegram-token
type: Opaque
stringData:
  token: ENC[AES256_GCM,data:GztJ7e5t6zGATcf5n/P0vg9kRFNU8qitso0HbDBu3+ObyyF6iqhDrptGEVlcZQ==,iv:IOMhO19BY03WOKC7nyeXO3HZbiMY2DArLjlF3y8p1Pw=,tag:Mtk+Ga/QzyNh4IY3esTMVg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2M09lMjRWNTFhVHFuYm9a
        ZGhwbFBMSCsweHhqUlRtQnlzRkFDY3dRbmwwCi9KcWhlaTRjV1ByUERrWUJEWTFw
        SjNjaVF2amhtYWJ0Z092TkFrdVlLQ2MKLS0tIDNWSDVCam1yS3oyT2xJYU14UlBu
        cG52OW9nM1Vvak1ONTBwbTM0b2I5OTgKYk+63NzvRXitG9H4drnDs40N1r1nbkoS
        G9dLL+mDRDyyYLwyMSvjdzPjmzkaIjrikg2Tl93gUpYCrZWs3CUwRg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age169tkyzjgmevv6qsm63yvmw5esv3d0mgpl85phljxw7ku235904pqg8qg3l
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-07T10:00:22Z"
  mac: ENC[AES256_GCM,data:d/joUWESJ5ndLCR2izv+0H386PYX6WX4B5UPm7fP2iHXwLtt5gLd4m2x/Q3GSMvBxHkGg/BnF6DYmqcnURUmpo3e0fcoH5CNB26kHvf6Lyup9CkjHwZYfh+xnHcOz0/fTQVVufAnTxkLQjHWEiKyzfFuLpMFpykaunStD6d7ob0=,iv:f3UhuiPAGzkn6gn5DBdrcnaxOtjNl0ZlGxBUDDESLfk=,tag:K52H25NyAQEzwdPtCnv0eg==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
