apiVersion: kustomize.config.k8s.io/v1beta1
configMapGenerator:
- files:
  - values.yaml=./helm/values.yaml
  name: cert-manager-values
configurations:
- ./helm/kustomizeconfig.yaml
kind: Kustomization
namespace: cert-manager
resources:
- ./clusterissuer.yaml
- ./helmrelease.yaml
- ./secret.sops.yaml
