# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:0qh/Hs12wNQE0v1t+PXH2mcfmFnTFtRnWMw/i0+SW6PwpFST8vbvh1ZByr/byVhW9l/oRUo=,iv:WhMry0Lf8M1+wCfZrxgyZtIz05Mk7UoIygc5lTn/y2g=,tag:3bKkXvKPxLMv8bQlnCgz9A==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTM0wzc0pXTXliZVBBWHhR
        aTZja2IxdTIrWVdzL25lNEZZaGk5QmxiakZVCmhJUnFJenB2RjJYZWpLR3FZeGFD
        ZmlXa09hbmpyYmVlUnZmci9xYXExQncKLS0tIFZSU3E5RWFpc0M2ekZXM3B0MnNB
        bjBUZ0tSYVcvbW8veGJ5S0V2QU5mRUEKDdtQ/vc48yRqEyd29I+P3TcQ3SYWPkUk
        EF0OLhQZ29+Fg9cQDUxUn/7h5OjzSLuHfPluc9U3vw0RtsDzGwfBHA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age169tkyzjgmevv6qsm63yvmw5esv3d0mgpl85phljxw7ku235904pqg8qg3l
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-05T07:24:26Z"
  mac: ENC[AES256_GCM,data:wlZUkKTUa7iP4+ob97m92o0/pasnrEXn2naS/WK8iuvpZHuhOrCkYib1DmjnGKYP/XAGyEOfqIPXl5koO6B4d6Jo1zFmJ1P1OsWIWz5w3487XWZldxIXXq2sdDjxckhp7IbFbg88F+aYWnYJnAKBs/9kxUyGt9rcZEJ1aBfrW3A=,iv:idnSC7Bu+7UH8GOLU073du7tIfbZIPUfnlcVUiu/8uQ=,tag:vC6aguRfkZWAhlhrzKp/Fw==,type:str]
  mac_only_encrypted: true
  version: 3.10.2
