# yaml-language-server: $schema=https://raw.githubusercontent.com/budimanjojo/talhelper/master/pkg/config/schemas/talconfig.json
---
clusterName: kubernetes

talosVersion: "${talosVersion}"
kubernetesVersion: "${kubernetesVersion}"

endpoint: https://10.57.57.88:6443
additionalApiServerCertSans: &sans
  - "127.0.0.1"
  - "10.57.57.88"
additionalMachineCertSans: *sans

clusterPodNets: ["10.42.0.0/16"]
clusterSvcNets: ["10.43.0.0/16"]

# Disable built-in CNI to use Cilium
cniConfig:
  name: none

nodes:
  - hostname: "kubernetes-controlplane-1"
    ipAddress: "10.57.57.80"
    installDisk: "/dev/sda"
    machineSpec:
      secureboot: false
    talosImageURL: factory.talos.dev/installer/ab86bd395e263b78e5f54c800e4d319dae786d9ae25ecb129462a9e0e9491615
    controlPlane: true
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "bc:24:11:a7:ba:13"
        dhcp: false
        addresses:
          - "10.57.57.80/24"
        routes:
          - network: "0.0.0.0/0"
            gateway: "10.57.57.1"
        mtu: 1500
        vip:
          ip: "10.57.57.88"
  - hostname: "kubernetes-controlplane-2"
    ipAddress: "10.57.57.82"
    installDisk: "/dev/sda"
    machineSpec:
      secureboot: false
    talosImageURL: factory.talos.dev/installer/ab86bd395e263b78e5f54c800e4d319dae786d9ae25ecb129462a9e0e9491615
    controlPlane: true
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "bc:24:11:a5:4b:9e"
        dhcp: false
        addresses:
          - "10.57.57.82/24"
        routes:
          - network: "0.0.0.0/0"
            gateway: "10.57.57.1"
        mtu: 1500
        vip:
          ip: "10.57.57.88"
  - hostname: "kubernetes-controlplane-3"
    ipAddress: "10.57.57.84"
    installDisk: "/dev/sda"
    machineSpec:
      secureboot: false
    talosImageURL: factory.talos.dev/installer/ab86bd395e263b78e5f54c800e4d319dae786d9ae25ecb129462a9e0e9491615
    controlPlane: true
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "bc:24:11:0e:cd:ab"
        dhcp: false
        addresses:
          - "10.57.57.84/24"
        routes:
          - network: "0.0.0.0/0"
            gateway: "10.57.57.1"
        mtu: 1500
        vip:
          ip: "10.57.57.88"


# Global patches
patches:
  - "@./patches/global/machine-files.yaml"
  - "@./patches/global/machine-longhorn.yaml"
  - "@./patches/global/machine-kubelet.yaml"
  - "@./patches/global/machine-network.yaml"
  - "@./patches/global/machine-sysctls.yaml"
  - "@./patches/global/machine-time.yaml"

# Controller patches
controlPlane:
  patches:
    - "@./patches/controller/admission-controller-patch.yaml"
    - "@./patches/controller/cluster.yaml"

# Worker patches
#worker:
#  patches:
#    - "@./patches/global/machine-longhorn-labels.yaml"
