apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonarr
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  volumeName: sonarr-restored-pv 
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonarr-cache
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 5Gi