---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyseerr
  namespace: default
  labels:
    recurring-job.longhorn.io/source: enabled
    recurring-job-group.longhorn.io/media: enabled
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyseerr-cache
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 5Gi
