apiVersion: v1
kind: Secret
metadata:
  name: netdata-secret
  namespace: default
stringData:
  CLAIMING_TOKEN: ENC[AES256_GCM,data:sD1zVQiY0DHQjDXb1ET7HSTtO/eNeOjkqrsMmWB7pg1plmT+oN9KriyIBw+Y8vcfUd7QsHTzvvjiAc/M7dpxJz1M3M4aBJpYrKrQ10bkXoknl0W2FHcU6bO4pC9URV61RrW24rcRZ8xAe/XF6BiP1jSYf9THIkk/DLHS9RJO6MyI08+EfQ/I,iv:t8v4vU+NnKX2KGB0DcIcCT3wX3EAfWgpWptqg6pwh68=,tag:tgE/TV5kw/Hh9BAS/jt67Q==,type:str]
sops:
  age:
    - recipient: age169tkyzjgmevv6qsm63yvmw5esv3d0mgpl85phljxw7ku235904pqg8qg3l
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPdmQ5N1RRL29UYWdValNT
        US9jK3ZEVFpDQkFwT1FhaTFtS1BYQ3dwbmlvCnFYbnpqeW42TWJ2OUZuR2xQVmZF
        ZkJhRWJOSnovU3lkM0szaUpsNEJyd2sKLS0tIEl6S2M5SWVUc294b2NtU2ZwdVpK
        a2tHL1EyOWowVGpROFI5UnFLM2NLVjQKdQ3buVtn222XLJNNAMzvbPsKf4oHHP+R
        lCtMTIC5lbb1r1Ykyb3g01pkO0ufX57rnnYK2SkORN62CJq1OlQgGQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-19T13:48:26Z"
  mac: ENC[AES256_GCM,data:QX7Ez6uL8yk7bF2IOAcOkqxoYMKGLfKIS4gzEcyEmkU10F7t6Ul2JmlMtPgtlLdgk9FbdOQeM2HdEsaf7DcqnWVn5c86nhJJ9kfCQ9XvAetAQqEDY2PReTQN18P3ofzF2UhHZDr2OJF/v1vdrIoB1jldZeo+0F2JiKmJdmV8bm8=,iv:aGjSCMG5odBwKAba7jMJlngrYqIUlk9TEZ35FzVQR7M=,tag:/wU5vWjJwiTjUOpWxiYSpQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
