apiVersion: v1
kind: Secret
metadata:
  name: minio-secret
  namespace: longhorn-system
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:EvdwCHmOex6aGGCZaob/0bpirUk/UUtoO18=,iv:e/sIXTzEjl5y5djnsCEDAtTqmXvVOaV19t94t3z4xMU=,tag:lwfvTnZCMyLZnMMdIS1clA==,type:str]
  AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:CgtQ3SU1f2W+DiEsk/uNbGyS/Z7mBGOaG6kRWiUpYLnufW9hYMUdGQ5QcPK63+LQzPxB/xeAiBMHMR0LreyKxg==,iv:Nwi+ZzRepUOF0CMQjiPh4R6OJ4qSzVcTTT0x4mKkaoM=,tag:uXzznPToHG4KsHduc/aWKg==,type:str]
  AWS_ENDPOINTS: ENC[AES256_GCM,data:thxwLa5Ia84vXVarg3AR+4kD+CExp/Q=,iv:s/8n/i6D428VEvcVeGtDvwSegI3R4xC64W672mnWBz4=,tag:K0E4AUtg1qpwqrYAcTVZvw==,type:str]
  AWS_REGION: ENC[AES256_GCM,data:7WV+o5LCt+vT,iv:OfDF555Z+LTGvv71t23lNTegFjnkqjEMifM7wymrLvA=,tag:a9ka+gPgvWAY8gaJcBgUHw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpV0JiZHhjaG1iRkROSnBt
        YmZDdjQ2dU5neGlxK2IvOHVmL3hKWHoxOW5nCnZsNVJnZklvNmRUa1lhVGRFU1Nj
        bWdTR1REWDRGRkd1Wm9PRDh3aDROWDgKLS0tIGxsaHR6ZFhRbFJZMnFyTlJQNnNQ
        YTErVHB5SENXMnNySFVHTVUwcDNuQU0K3hvpW+EvTktDPCV9vV/J8Kfo1noQR9im
        GSSVtXVzcsQgKsy1ATvaAoUbYRyWJW9YX/hKf+hKownTlAzMaZCOHg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age169tkyzjgmevv6qsm63yvmw5esv3d0mgpl85phljxw7ku235904pqg8qg3l
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-21T16:38:26Z"
  mac: ENC[AES256_GCM,data:3nqyZFE2aHSBL8veBdMG7YRLThh1FtfCP7Fn5QuISD3lrKkc14SZDEsONdo1s1vpAZLjaN4Sgkd8egdmLl7eExtTvJBMX/mFk+wQOOsyovcCVIMWZtlwIMajeekKJdum9XF8U5ZEUkWPLeJDp3QMnWI04jaNKFIihRN9HCDvlro=,iv:V3pt09VnCVICxd6laLSnuSWnga41AHc1LRMH7r/iFcE=,tag:vouDpJoK2doDCZ++rZp1Fg==,type:str]
  mac_only_encrypted: true
  version: 3.13.2
