apiVersion: v1
kind: Secret
metadata:
  name: minio-secret
  namespace: longhorn-system
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:t45nli6A4C8SKUqayUdYqowiJZpIJe6Xfsg=,iv:p6rMycCy0SK1a8eUg9t1MQFpET04IO8GQy2DROqOaUE=,tag:SvN0Q6cijnljJEDATCF1tQ==,type:str]
  AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:RY8iXqCF5IlkYB4bmd2gUlzpv5I9KBsMXXrC86GtceOcz1EtJ84GcC0JZRltQTlzUaAEZlJOIrhKWL8acZlypQ==,iv:m74e/zI6VCvxVD5Ud7DqtC62hrVKqYqIXM7sKKCK6/U=,tag:Wk84hrgsL77gy1/bRgESUQ==,type:str]
  AWS_ENDPOINTS: ENC[AES256_GCM,data:emc/rC/UURkrEkMGos///89NuSPTa8E=,iv:zCzY5W33SNPPr5EzphHsIjdF6mfXDupyKPCakKZJ0HE=,tag:iziT1fMO8pFK7QdfLXVwzw==,type:str]
  AWS_REGION: ENC[AES256_GCM,data:7WV+o5LCt+vT,iv:OfDF555Z+LTGvv71t23lNTegFjnkqjEMifM7wymrLvA=,tag:a9ka+gPgvWAY8gaJcBgUHw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpV0JiZHhjaG1iRkROSnBt
        YmZDdjQ2dU5neGlxK2IvOHVmL3hKWHoxOW5nCnZsNVJnZklvNmRUa1lhVGRFU1Nj
        bWdTR1REWDRGRkd1Wm9PRDh3aDROWDgKLS0tIGxsaHR6ZFhRbFJZMnFyTlJQNnNQ
        YTErVHB5SENXMnNySFVHTVUwcDNuQU0K3hvpW+EvTktDPCV9vV/J8Kfo1noQR9im
        GSSVtXVzcsQgKsy1ATvaAoUbYRyWJW9YX/hKf+hKownTlAzMaZCOHg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age169tkyzjgmevv6qsm63yvmw5esv3d0mgpl85phljxw7ku235904pqg8qg3l
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-29T17:30:49Z"
  mac: ENC[AES256_GCM,data:8AaqBX9CvMHlh6Dwr72MUq7BO+86dUFR5xfzVrbjQNMIFhJrpfeFzD/3h75pK3f2t5ZNB3UV8IOWMKpBSGkvtCZUGin3CPSPqm0eNpNPnWswo13Xmz9v6gz3cJGH1GhcyexI9ihPbUKc5bda8zptECixzogbVe+NVT9UmF0JABk=,iv:X2k+OjQDRgF/qAuJP3NG6RO2sgel5fyktJTPxaci5cY=,tag:GaRbpVgU1ZEA18E0rJN5XQ==,type:str]
  mac_only_encrypted: true
  version: 3.13.2
