# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app homepage
  namespace: default
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.7.3
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    controllers:
      homepage:
        strategy: RollingUpdate
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/gethomepage/homepage
              tag: v1.3.2@sha256:4f923bf0e9391b3a8bc5527e539b022e92dcc8a3a13e6ab66122ea9ed030e196
            env:
              TZ: Europe/Bucharest
              HOMEPAGE_ALLOWED_HOSTS: dashboard.k8s.${SECRET_DOMAIN}
            envFrom:
              - secretRef:
                  name: homepage-secret
            probes:
              startup:
                enabled: true
                spec:
                  failureThreshold: 30
                  periodSeconds: 5
              liveness:
                enabled: true
              readiness:
                enabled: true
            resources:
              requests:
                cpu: 100m
                memory: 128Mi
              limits:
                cpu: 500m
                memory: 256Mi
            securityContext:
              allowPrivilegeEscalation: false
              capabilities:
                drop:
                  - ALL
              fsGroup: 1000
              fsGroupChangePolicy: "OnRootMismatch"
              readOnlyRootFilesystem: true
              runAsGroup: 1000
              runAsNonRoot: true
              runAsUser: 1000
    serviceAccount:
      create: true
      name: homepage
    service:
      homepage:
        controller: homepage
        ports:
          http:
            port: 3000
    persistence:
      config:
        enabled: true
        type: configMap
        name: homepage-config
        globalMounts:
          - subPath: docker.yaml
            path: /app/config/docker.yaml
            readOnly: true
          - subPath: kubernetes.yaml
            path: /app/config/kubernetes.yaml
            readOnly: true
          - subPath: services.yaml
            path: /app/config/services.yaml
            readOnly: true
          - subPath: settings.yaml
            path: /app/config/settings.yaml
            readOnly: true
          - subPath: widgets.yaml
            path: /app/config/widgets.yaml
            readOnly: true
      bookmarks:
        enabled: true
        type: secret
        name: homepage-secret
        globalMounts:
          - subPath: bookmarks.yaml
            path: /app/config/bookmarks.yaml
            readOnly: true
      logs:
        enabled: true
        type: emptyDir
        globalMounts:
          - path: /app/config/logs
    ingress:
      homepage:
        enabled: true
        className: internal
        hosts:
          - host: dashboard.k8s.${SECRET_DOMAIN}
            paths:
              - path: /
                service:
                  identifier: homepage
                  port: http