kind: Secret
apiVersion: v1
type: Opaque
metadata:
  name: immich-postgres-secret
stringData:
  password: ENC[AES256_GCM,data:v64dnfwwjuvdQCwrKNMM7KqY04eMT7H+uNx7vKcf,iv:QZC9SsGwlc3PIsK4GY/SpnN6eACQIxOrCSDOMFSeGes=,tag:FLA9ltL50cYHYKWJNKGQpg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxb3BXaHJmWCtRME5wR2tm
        YmtnM0xtS1JlVURPejVBSjd0NmlldDVERGlnClB1TW44R2o1QVFlaS9jODhSdy92
        aU9aVDFoNVF0WUZiYTdtbnNnajJXd0EKLS0tIDJORnZINTgrd1B0WnJ5VWNHUDZo
        bk9SWC84cnRkWTArRDRYdFpoc0RuRE0KDnRR4tOvWRejVHAMgzfBbw+UsVT8PGPl
        bmMPBGXXzo862Pk66PtJKDCY6FkFxXI7Qvo/6/qh17qzQA7N7kj13w==
        -----END AGE ENCRYPTED FILE-----
      recipient: age169tkyzjgmevv6qsm63yvmw5esv3d0mgpl85phljxw7ku235904pqg8qg3l
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-22T17:49:41Z"
  mac: ENC[AES256_GCM,data:AiuPOYlDHZ++JBMbqa3/nwLGysn5s3eErX79IOfJUpFVTjXclLV/oE6Ra/OwDJX2r/QMbNz+XY29olYMiJuUCSswELLSrK96B3JTt7N4PnEhea2g4/877l70bkZdVNOIEbp1SnSJWWb7JTIDS2H7onBy7bA7OPcny6gVsq9RH6w=,iv:OZ4A/c6A7IQD7YE+ErW0yhzJwBtptFngELw3oN/ryY8=,tag:jZI7xCaaVxD9Db3UVp8trw==,type:str]
  mac_only_encrypted: true
  version: 3.13.2
