kind: Secret
apiVersion: v1
type: Opaque
metadata:
  name: immich-postgres-secret
stringData:
  password: ENC[AES256_GCM,data:MIOmJjjmt3dPP8Bw0tBThs23P+sGk/uXKd1xhACA,iv:v0CG/5/qM7yS78pxfS0kp+UtS5qz6dM/WfnJufg5l/c=,tag:fLo9v1BH86gbaQeDHaZePA==,type:str]
  hc_ping_url: ""
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age169tkyzjgmevv6qsm63yvmw5esv3d0mgpl85phljxw7ku235904pqg8qg3l
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByY3F4YlNackl4MXdtUU03
        SHBKQkZQd25LbkNOOVJmelJCVkZiNWM0RUcwCjRxN2NRa1hnVFArc25kdlFwM0Z6
        TWQzTitpQXQydTNxbGxDN3VyWDgxa0EKLS0tIEQwQ1pmNE9aMkM3TVBpNFdmNFlv
        K1RnN1BTWkFkYkJ0MjhNNC9WNzFiMk0KXoPgsasENb/VoCxQscpdSoTum1BHfEg+
        8wa+/eTbU2zvoQrB1bDIwNdPIuLzBr9pt76z55dOgIL3cCidAbwTSA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-07-24T11:45:45Z"
  mac: ENC[AES256_GCM,data:L33T2YoP0ZFT2I38S2E1Rawf1YYOU+o5aMfKJxi7uAhrH5Cn3u0XZlewRpsr8iyNvk4uNWu5bTeihBOWFIhWEf3ry6gad4L6YPCG+jnuQ0zJ5Q8vmkEy1mWlQply3MsNxUjCIn+5dcWEatyBzFYDrG6xdwiqOTEf233d4AuIE+g=,iv:78zCZOAyIRgyrwE5JZEHpPRWvYXHGfSdsaZkQL4hMUQ=,tag:OBgLJ3NKLdKKXhW2U/zpyg==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
