apiVersion: v1
kind: Secret
metadata:
  name: qbtools-config-secret
  namespace: default
stringData:
  config.yaml: ENC[AES256_GCM,data:CWhuh3Y1CJHgBOjH22UT+4ghobaFRZqC6b1LaOULqzSfjrblSpiPQ+sLgXhP8s6awQ==,iv:s9N60d6uj8JXxUqzHnLsGaVAMB56vriLeZDYYEs1mKI=,tag:WosbPg2OCAeS6vp94ygd2g==,type:str]
sops:
  age:
    - recipient: age169tkyzjgmevv6qsm63yvmw5esv3d0mgpl85phljxw7ku235904pqg8qg3l
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByN3BnWXlnMkUvSTdFNjE0
        Qm1mTDFzdW1MbVMrY1ZrVDVmVFN3WGNJT2tZCkNSdEhBdStNTHpYVlZwUjdpd1ZT
        M0xHZFVSMWIvVTY4Zi9vekhVemxzMWMKLS0tIHJIUVVQWlhYYjBJamhBbXJycEh0
        bktrK2grU3lvMTJhMmRkSm1wU0h5dUkKRZskvshePRqbiqEMdQN+z00c1Tl8p4+i
        ci5d8BzZtu0SDQ8OHu8S7SYs1Ur5FYhBZr9GwtHOn+o4r1HigBboAA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-06-26T07:22:06Z"
  mac: ENC[AES256_GCM,data:awkVhQu05pjzO9RpxF5uutFGZtuNWpJQaAZeA9+q3GnCOO2mqd6z8YaAeNOll9PgLpOAL4ooCuh7qZVIP7xr3Cx39b5cKsihjXv8nGBqpHEAtOSeeWPpQxWuwq4nujXxx0KojE2f3/Eb/GtwxlrIBWnpyZqAuWL3IIQLroQ3LeQ=,iv:NhjKgyMWTET292SIoeG0cTZAiuLAf8CX8XnFpcLYVrc=,tag:ks3ldzx6P94dXnxb5UQkKg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
