---
# Handlers for initial_setup role

- name: restart cron
  ansible.builtin.systemd:
    name: cron
    state: restarted

- name: restart ssh
  ansible.builtin.systemd:
    name: ssh
    state: restarted

- name: restart timesyncd
  ansible.builtin.systemd:
    name: systemd-timesyncd
    state: restarted
