apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:G40hVAWClFWQ,iv:PxGn6P4wXmIqJfnXfyZoLP3kSUIeqInAZWtcc8OZy64=,tag:YPbP+U5mtfMIFUw+0UwQfw==,type:str]
sops:
  age:
    - recipient: age169tkyzjgmevv6qsm63yvmw5esv3d0mgpl85phljxw7ku235904pqg8qg3l
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFMjlxdW93QXRuT3h4eEZN
        eUIyaXZ0RHA0T3JNNS96SWVLcjJuMmp3WXk4Ck93TnU5RW8xSG5meUVHdWtkOERy
        NkpmUExqNU9ReGxZODRJNXA2VEJaSDgKLS0tIEdYL2NYUy9MUEMxK1NMdFg2R3p1
        cDZEazNEeUd0NkZGTnhOYlZNVFp3MjAKDmretP+PAib5yaUd4rXWrFrqv8Z71+HN
        SeBQmdCdKMaMwNPCmR9xUghbV1w+n42J78uyoi3I9wsVzKpK4dDTWg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-06-15T17:51:28Z"
  mac: ENC[AES256_GCM,data:1mKfWtxrVNvZo+Xr83bXXH+W3M4CHhS38jUaXEAOHZB7OGL2fk8PUNcfZRYA9wqV2ZxaATX9SFKbZL0GNyFKgKMA8CuWNCFXV3yotG4ZYPkCiX29a+EI9oMHl9RM78DiXtr2/A722nE3UCl6d2X7OsdJ1x98mhwMmvsN/+dB9qc=,iv:bl2mGts1nziItsjxRNU4+Ub6eAEsZ+T00fIiOborhEM=,tag:lIWUJEO3s+wyYyzkEfHKow==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
