---
# yaml-language-server: $schema=https://datreeio.github.io/CRDs-catalog/cilium.io/ciliumnetworkpolicy_v2.json
# Exception to ../../network-policy.yaml's default-deny: Jellyseerr submits
# requests to Radarr's API.
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: radarr-public-ingress
spec:
  endpointSelector:
    matchLabels:
      app.kubernetes.io/name: radarr-public
  ingress:
    - fromEndpoints:
        - matchLabels:
            app.kubernetes.io/name: jellyseerr
      toPorts:
        - ports:
            - port: "80"
              protocol: TCP
